
name: Build and Deploy to GitHub Pages

on:
  push:
    branches:
      - main # ou master, dependendo da sua branch principal

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.8' # Use a versão exata do seu Flutter

      - name: Install Dependencies
        run: flutter pub get

      - name: Build Web App
        run: flutter build web --release --base-href="/calc_construtor/"

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/web